

// Added by the Spring Security Core plugin:
grails.plugin.springsecurity.userLookup.userDomainClassName = 'apps.User'
grails.plugin.springsecurity.userLookup.authorityJoinClassName = 'apps.UserRole'
grails.plugin.springsecurity.authority.className = 'apps.Role'
grails.plugin.springsecurity.controllerAnnotations.staticRules = [
	[pattern: '/',               access: ['permitAll']],
	[pattern: '/error',          access: ['permitAll']],
	[pattern: '/index',          access: ['permitAll']],
	[pattern: '/index.gsp',      access: ['permitAll']],
	[pattern: '/shutdown',       access: ['permitAll']],
	[pattern: '/assets/**',      access: ['permitAll']],
	[pattern: '/**/js/**',       access: ['permitAll']],
	[pattern: '/**/css/**',      access: ['permitAll']],
	[pattern: '/**/images/**',   access: ['permitAll']],
	[pattern: '/**/favicon.ico', access: ['permitAll']],
	[pattern: '/product/twitter',        access: ['permitAll']],
	[pattern: '/product/twitterLoggedIn',access: ['permitAll']],
	[pattern: '/product/twitterUserData',access: ['permitAll']],
	[pattern: '/product/twitterg20',access: ['permitAll']],
	[pattern: '/product/twitterBrics',access: ['permitAll']],
	[pattern: '/product/twitterPanamaPapers',access: ['permitAll']],
	[pattern: '/product/twitterHeadline',access: ['permitAll']],
	[pattern: '/product/twitterTrump',access: ['permitAll']],
	[pattern: '/product/twitterVenture',access: ['permitAll']],
	[pattern: '/product/twitterEntertainment',access: ['permitAll']],
	[pattern: '/product/twitterDefense',access: ['permitAll']],
	[pattern: '/product/twitterYoga',access: ['permitAll']],
	[pattern: '/product/twitterHillary',access: ['permitAll']],
	[pattern: '/product/twitterThiel',access: ['permitAll']],
	[pattern: '/product/retweet',access: ['permitAll']],
	[pattern: '/product/favorite',access: ['permitAll']],
	[pattern: '/tweet/index',access: ['permitAll']],
	[pattern: '/tweet/show',access: ['permitAll']],
	[pattern: '/product/premium',access: ['permitAll']],
	[pattern: '/product/seller',access: ['permitAll']],
	[pattern: '/tweet/archiveG20',access: ['permitAll']],
	[pattern: '/tweet/archiveBrics',access: ['permitAll']],
	[pattern: '/tweet/archivePanamaPapers',access: ['permitAll']],
	[pattern: '/tweet/archiveRussiaGate',access: ['permitAll']],
	[pattern: '/tweet/archiveDefense',access: ['permitAll']],
	[pattern: '/tweet/archiveTrump',access: ['permitAll']],
	[pattern: '/tweet/archiveStartups',access: ['permitAll']],
	[pattern: '/tweet/archiveYoga',access: ['permitAll']],
	[pattern: '/product/processLogin',access: ['permitAll']],
	[pattern: '/checkout/productCheckout',access: ['permitAll']],
	[pattern: '/product/help',access: ['permitAll']],
	[pattern: '/product/software',access: ['permitAll']],
	[pattern: '/product/loop',access: ['permitAll']],
	[pattern: '/product/mom',access: ['permitAll']],
	[pattern: '/product/dad',access: ['permitAll']],
	[pattern: '/product/male',access: ['permitAll']],
	[pattern: '/product/female',access: ['permitAll']],
	[pattern: '/product/demo',access: ['permitAll']],
	[pattern: '/product/demo2',access: ['permitAll']],
	[pattern: '/product/demo3',access: ['permitAll']],
	[pattern: '/product/demo4',access: ['permitAll']],
	[pattern: '/product/demo5',access: ['permitAll']],
	[pattern: '/product/demo6',access: ['permitAll']],
	[pattern: '/product/m',access: ['permitAll']],
	[pattern: '/product/n',access: ['permitAll']],
	[pattern: '/product/o',access: ['permitAll']],
	[pattern: '/product/p',access: ['permitAll']],
	[pattern: '/product/q',access: ['permitAll']],
	[pattern: '/product/r',access: ['permitAll']],
	[pattern: '/product/i',access: ['permitAll']],
	[pattern: '/product/j',access: ['permitAll']],
	[pattern: '/product/k',access: ['permitAll']],
	[pattern: '/product/l',access: ['permitAll']]
]

grails.plugin.springsecurity.filterChain.chainMap = [
	[pattern: '/assets/**',      filters: 'none'],
	[pattern: '/**/js/**',       filters: 'none'],
	[pattern: '/**/css/**',      filters: 'none'],
	[pattern: '/**/images/**',   filters: 'none'],
	[pattern: '/**/favicon.ico', filters: 'none'],
	[pattern: '/**',             filters: 'JOINED_FILTERS']
]



// Added by the Spring Security Core plugin:
grails.plugin.springsecurity.userLookup.userDomainClassName = 'apps.User'
grails.plugin.springsecurity.userLookup.authorityJoinClassName = 'apps.UserRole'
grails.plugin.springsecurity.authority.className = 'apps.Role'
grails.plugin.springsecurity.controllerAnnotations.staticRules = [
	[pattern: '/',               access: ['permitAll']],
	[pattern: '/error',          access: ['permitAll']],
	[pattern: '/index',          access: ['permitAll']],
	[pattern: '/index.gsp',      access: ['permitAll']],
	[pattern: '/shutdown',       access: ['permitAll']],
	[pattern: '/assets/**',      access: ['permitAll']],
	[pattern: '/**/js/**',       access: ['permitAll']],
	[pattern: '/**/css/**',      access: ['permitAll']],
	[pattern: '/**/images/**',   access: ['permitAll']],
	[pattern: '/**/favicon.ico', access: ['permitAll']],
	[pattern: '/product/twitter',        access: ['permitAll']],
	[pattern: '/product/twitterLoggedIn',access: ['permitAll']],
	[pattern: '/product/twitterUserData',access: ['permitAll']],
	[pattern: '/product/twitterg20',access: ['permitAll']],
	[pattern: '/product/twitterBrics',access: ['permitAll']],
	[pattern: '/product/twitterPanamaPapers',access: ['permitAll']],
	[pattern: '/product/twitterHeadline',access: ['permitAll']],
	[pattern: '/product/twitterTrump',access: ['permitAll']],
	[pattern: '/product/twitterVenture',access: ['permitAll']],
	[pattern: '/product/twitterEntertainment',access: ['permitAll']],
	[pattern: '/product/twitterDefense',access: ['permitAll']],
	[pattern: '/product/twitterYoga',access: ['permitAll']],
	[pattern: '/product/twitterHillary',access: ['permitAll']],
	[pattern: '/product/twitterThiel',access: ['permitAll']],
	[pattern: '/product/retweet',access: ['permitAll']],
	[pattern: '/product/favorite',access: ['permitAll']],
	[pattern: '/tweet/index',access: ['permitAll']],
	[pattern: '/tweet/show',access: ['permitAll']],
	[pattern: '/product/premium',access: ['permitAll']],
	[pattern: '/product/seller',access: ['permitAll']],
	[pattern: '/tweet/archiveG20',access: ['permitAll']],
	[pattern: '/tweet/archiveBrics',access: ['permitAll']],
	[pattern: '/tweet/archivePanamaPapers',access: ['permitAll']],
	[pattern: '/tweet/archiveRussiaGate',access: ['permitAll']],
	[pattern: '/tweet/archiveDefense',access: ['permitAll']],
	[pattern: '/tweet/archiveTrump',access: ['permitAll']],
	[pattern: '/tweet/archiveStartups',access: ['permitAll']],
	[pattern: '/tweet/archiveYoga',access: ['permitAll']],
	[pattern: '/product/processLogin',access: ['permitAll']],
	[pattern: '/checkout/productCheckout',access: ['permitAll']],
	[pattern: '/product/help',access: ['permitAll']],
	[pattern: '/product/software',access: ['permitAll']],
	[pattern: '/product/loop',access: ['permitAll']],
	[pattern: '/product/mom',access: ['permitAll']],
	[pattern: '/product/dad',access: ['permitAll']],
	[pattern: '/product/male',access: ['permitAll']],
	[pattern: '/product/female',access: ['permitAll']],
	[pattern: '/product/demo',access: ['permitAll']],
	[pattern: '/product/demo2',access: ['permitAll']],
	[pattern: '/product/demo3',access: ['permitAll']],
	[pattern: '/product/demo4',access: ['permitAll']],
	[pattern: '/product/demo5',access: ['permitAll']],
	[pattern: '/product/demo6',access: ['permitAll']],
	[pattern: '/product/m',access: ['permitAll']],
	[pattern: '/product/n',access: ['permitAll']],
	[pattern: '/product/o',access: ['permitAll']],
	[pattern: '/product/p',access: ['permitAll']],
	[pattern: '/product/q',access: ['permitAll']],
	[pattern: '/product/r',access: ['permitAll']],
	[pattern: '/product/i',access: ['permitAll']],
	[pattern: '/product/j',access: ['permitAll']],
	[pattern: '/product/k',access: ['permitAll']],
	[pattern: '/product/l',access: ['permitAll']]
]

grails.plugin.springsecurity.filterChain.chainMap = [
	[pattern: '/assets/**',      filters: 'none'],
	[pattern: '/**/js/**',       filters: 'none'],
	[pattern: '/**/css/**',      filters: 'none'],
	[pattern: '/**/images/**',   filters: 'none'],
	[pattern: '/**/favicon.ico', filters: 'none'],
	[pattern: '/**',             filters: 'JOINED_FILTERS']
]



// Added by the Spring Security Core plugin:
grails.plugin.springsecurity.userLookup.userDomainClassName = 'apps.User'
grails.plugin.springsecurity.userLookup.authorityJoinClassName = 'apps.UserRole'
grails.plugin.springsecurity.authority.className = 'apps.Role'
grails.plugin.springsecurity.controllerAnnotations.staticRules = [
	[pattern: '/',               access: ['permitAll']],
	[pattern: '/error',          access: ['permitAll']],
	[pattern: '/index',          access: ['permitAll']],
	[pattern: '/index.gsp',      access: ['permitAll']],
	[pattern: '/shutdown',       access: ['permitAll']],
	[pattern: '/assets/**',      access: ['permitAll']],
	[pattern: '/**/js/**',       access: ['permitAll']],
	[pattern: '/**/css/**',      access: ['permitAll']],
	[pattern: '/**/images/**',   access: ['permitAll']],
	[pattern: '/**/favicon.ico', access: ['permitAll']],
	[pattern: '/product/twitter',        access: ['permitAll']],
	[pattern: '/product/twitterLoggedIn',access: ['permitAll']],
	[pattern: '/product/twitterUserData',access: ['permitAll']],
	[pattern: '/product/twitterg20',access: ['permitAll']],
	[pattern: '/product/twitterBrics',access: ['permitAll']],
	[pattern: '/product/twitterPanamaPapers',access: ['permitAll']],
	[pattern: '/product/twitterHeadline',access: ['permitAll']],
	[pattern: '/product/twitterTrump',access: ['permitAll']],
	[pattern: '/product/twitterVenture',access: ['permitAll']],
	[pattern: '/product/twitterEntertainment',access: ['permitAll']],
	[pattern: '/product/twitterDefense',access: ['permitAll']],
	[pattern: '/product/twitterYoga',access: ['permitAll']],
	[pattern: '/product/twitterHillary',access: ['permitAll']],
	[pattern: '/product/twitterThiel',access: ['permitAll']],
	[pattern: '/product/retweet',access: ['permitAll']],
	[pattern: '/product/favorite',access: ['permitAll']],
	[pattern: '/tweet/index',access: ['permitAll']],
	[pattern: '/tweet/show',access: ['permitAll']],
	[pattern: '/product/premium',access: ['permitAll']],
	[pattern: '/product/seller',access: ['permitAll']],
	[pattern: '/tweet/archiveG20',access: ['permitAll']],
	[pattern: '/tweet/archiveBrics',access: ['permitAll']],
	[pattern: '/tweet/archivePanamaPapers',access: ['permitAll']],
	[pattern: '/tweet/archiveRussiaGate',access: ['permitAll']],
	[pattern: '/tweet/archiveDefense',access: ['permitAll']],
	[pattern: '/tweet/archiveTrump',access: ['permitAll']],
	[pattern: '/tweet/archiveStartups',access: ['permitAll']],
	[pattern: '/tweet/archiveYoga',access: ['permitAll']],
	[pattern: '/product/processLogin',access: ['permitAll']],
	[pattern: '/checkout/productCheckout',access: ['permitAll']],
	[pattern: '/product/help',access: ['permitAll']],
	[pattern: '/product/software',access: ['permitAll']],
	[pattern: '/product/loop',access: ['permitAll']],
	[pattern: '/product/mom',access: ['permitAll']],
	[pattern: '/product/dad',access: ['permitAll']],
	[pattern: '/product/male',access: ['permitAll']],
	[pattern: '/product/female',access: ['permitAll']],
	[pattern: '/product/demo',access: ['permitAll']],
	[pattern: '/product/demo2',access: ['permitAll']],
	[pattern: '/product/demo3',access: ['permitAll']],
	[pattern: '/product/demo4',access: ['permitAll']],
	[pattern: '/product/demo5',access: ['permitAll']],
	[pattern: '/product/demo6',access: ['permitAll']],
	[pattern: '/product/m',access: ['permitAll']],
	[pattern: '/product/n',access: ['permitAll']],
	[pattern: '/product/o',access: ['permitAll']],
	[pattern: '/product/p',access: ['permitAll']],
	[pattern: '/product/q',access: ['permitAll']],
	[pattern: '/product/r',access: ['permitAll']],
	[pattern: '/product/i',access: ['permitAll']],
	[pattern: '/product/j',access: ['permitAll']],
	[pattern: '/product/k',access: ['permitAll']],
	[pattern: '/product/l',access: ['permitAll']]
]

grails.plugin.springsecurity.filterChain.chainMap = [
	[pattern: '/assets/**',      filters: 'none'],
	[pattern: '/**/js/**',       filters: 'none'],
	[pattern: '/**/css/**',      filters: 'none'],
	[pattern: '/**/images/**',   filters: 'none'],
	[pattern: '/**/favicon.ico', filters: 'none'],
	[pattern: '/**',             filters: 'JOINED_FILTERS']
]

grails.plugin.springsecurity.ui.register.defaultRoleNames = ['ROLE_ADMIN']
grails.plugin.springsecurity.ui.register.emailSubject = 'Welcome to Foodal!'
